// /* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// export const projectId = "qnvcnsvfknmwrpelrgko"
// export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFudmNuc3Zma25td3JwZWxyZ2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODEzNTUsImV4cCI6MjA3MzM1NzM1NX0.G512jiBPK9nexQo1aSDH5ro9J9mCIdKAzycwBElXlAg"